# CapStone-ToDo-2

trigger:
  branches:
    include:
      - master
      - north
      - south
    exclude:
      - north-*
      - south-*

pool:
  vmImage: 'windows-latest' # Required for FileTransform@2 task

stages:
- stage: 'build_capstone'
  displayName: '1. Build BackEnd and FrontEnd packages'
  variables:
    - group: build

  jobs:
  - job: 'build_capstone_backend'
    displayName: '1.1. Build BackEnd'

    steps:

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '--configuration Release'
        workingDirectory: $(Build.SourcesDirectory)/capstone.web.api
      displayName: '1.1.1. Build: Build using Solution File'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/*.sln'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/capstone.web.api'
        modifyOutputPath: false
        publishWebProjects: false
        zipAfterPublish: true
      displayName: '1.1.2. Publish: Create Archive Package in Staging Directory'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/capstone.web.api'
        artifact: 'capstone.web.api'
        publishLocation: 'pipeline'
      displayName: '1.1.3. Publish: Publish BackEnd Build as a Pipeline Artifact'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'tool'
        arguments: 'install --global dotnet-ef'
      displayName: '1.1.4. Setup: Install Entity Framework tool'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'custom'
        custom: 'ef'
        arguments: 'migrations script --idempotent --configuration Release --project $(Build.SourcesDirectory)/capstone.web.api --context AppDbContext --startup-project $(Build.SourcesDirectory)/capstone.web.api --output $(Build.ArtifactStagingDirectory)/capstone.web.db/capstone.web.db.sql'
      displayName: '1.1.5. Build: Generate Database Script'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/capstone.web.db/capstone.web.db.sql'
        artifact: 'capstone.web.db'
        publishLocation: 'pipeline'
      displayName: '1.1.6. Publish: Publish Database Script as a Pipeline Artifact'

  - job: 'build_capstone_frontend'
    displayName: '1.2. Build FrontEnd'

    steps:
    - task: UseNode@1
      inputs:
        version: '20.x'
      displayName: '1.2.1. Setup: Install Node.js'

    - script: |
        npm install --global @angular/cli
      workingDirectory: $(Build.SourcesDirectory)/capstone.web
      displayName: '1.2.2. Setup: Install Angular'

    - script: |
        npm install
      workingDirectory: $(Build.SourcesDirectory)/capstone.web
      displayName: '1.2.3. Setup: Install Packages'

    - script: |
        npm run ng build --configuration=production --optimization=true
      workingDirectory: $(Build.SourcesDirectory)/capstone.web
      displayName: '1.2.4. Build: Create Production Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/capstone.web/dist/capstone.web'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/capstone.web/capstone.web.zip'
        verbose: true
      displayName: '1.2.5. Publish: Create Archive Package in Staging Directory'

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/capstone.web'
        artifact: 'capstone.web'
        publishLocation: 'pipeline'
      displayName: '1.2.6. Publish: Publish FrontEnd Build as a Pipeline Artifact'

- stage: 'deploy_capstone_test'
  displayName: '2. Deploy to Test Environment'
  dependsOn:
    - build_capstone
  variables:
    - group: test

  jobs:
    - deployment: deploy_capstone_test_backend
      displayName: '2.1. Deploy BackEnd to Test'
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'capstone.web.api'
                targetPath: '$(Pipeline.Workspace)/capstone.web.api'
              displayName: '2.1.1. Retrieve: Download BackEnd Pipeline Artifacts'

            - task: FileTransform@2
              inputs:
                folderPath: '$(Pipeline.Workspace)/capstone.web.api/*.zip'
                jsonTargetFiles: '**/appsettings.json'
              displayName: '2.1.2. Replace: Adjust Database Connection String'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webApp'
                appName: '$(deployBackEnd)'
                package: '$(Pipeline.Workspace)/capstone.web.api/*.zip'
                deploymentMethod: 'auto'
              displayName: '2.1.3. Deploy: Deploy Azure Web App for Windows'

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'capstone.web.db'
                targetPath: '$(Pipeline.Workspace)/capstone.web.db'
              displayName: '2.1.4. Retrieve: Download Database Pipeline Artifacts'

            # - task: SqlAzureDacpacDeployment@1
            #   inputs:
            #     azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
            #     AuthenticationType: 'connectionString'
            #     ConnectionString: '$(deployDatabase)'
            #     deployType: 'SqlTask'
            #     SqlFile: '$(Pipeline.Workspace)/capstone.web.db/capstone.web.db.sql'
            #   displayName: '2.1.5. Deploy: Update Database'

    - deployment: deploy_capstone_test_frontend
      displayName: '2.2. Deploy FrontEnd to Test'
      dependsOn: deploy_capstone_test_backend
      environment: test
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'capstone.web'
                targetPath: '$(Pipeline.Workspace)/capstone.web'
              displayName: '2.2.1. Retrieve: Download Pipeline Artifacts'

            - task: ExtractFiles@1
              inputs:
                archiveFilePatterns: '$(Pipeline.Workspace)/capstone.web/*.zip'
                destinationFolder: '$(Pipeline.Workspace)/capstone.web/dist'
              displayName: '2.2.2. Retrieve: Extract Artifacts'

            - task: replacetokens@3
              inputs:
                targetFiles: '$(Pipeline.Workspace)/capstone.web/dist/**/main*.js'
                encoding: 'auto'
                writeBOM: true
                verbosity: 'detailed'
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                useLegacyPattern: false
                enableTelemetry: true
              displayName: '2.2.3. Replace: Replace BackEnd URL'

            - task: ArchiveFiles@2
              inputs:
                rootFolderOrFile: '$(Pipeline.Workspace)/capstone.web/dist'
                includeRootFolder: false
                archiveType: 'zip'
                archiveFile: '$(Pipeline.Workspace)/capstone.web/capstone.web.updated.zip'
                verbose: true
              displayName: '2.2.4. Replace: Create Archive Package in Pipeline Directory'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webAppLinux'
                appName: '$(deployFrontEnd)'
                package: '$(Pipeline.Workspace)/capstone.web/capstone.web.updated.zip' 
                deploymentMethod: 'auto'
              displayName: '2.2.5. Deploy: Deploy Azure Web App for Linux'

- stage: 'deploy_capstone_prod'
  displayName: '3. Deploy to Production Environment'
  dependsOn:
    - build_capstone
    - deploy_capstone_test
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  variables:
    - group: prod

  jobs:
    - deployment: deploy_capstone_prod_backend
      displayName: '3.1. Deploy BackEnd to Prod'
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
            - download: none

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'capstone.web.api'
                targetPath: '$(Pipeline.Workspace)/capstone.web.api'
              displayName: '3.1.1. Retrieve: Download Pipeline Artifacts'

            - task: FileTransform@2
              inputs:
                folderPath: '$(Pipeline.Workspace)/capstone.web.api/*.zip'
                jsonTargetFiles: '**/appsettings.json'
              displayName: '3.1.2. Replace: Adjust Database Connection String'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                appType: 'webApp'
                appName: '$(deployBackEnd)'
                package: '$(Pipeline.Workspace)/capstone.web.api/*.zip'
                deploymentMethod: 'auto'
              displayName: '3.1.3. Deploy: Deploy Azure Web App for Windows'

            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'capstone.web.db'
                targetPath: '$(Pipeline.Workspace)/capstone.web.db'
              displayName: '3.1.4. Retrieve: Download Database Pipeline Artifacts'

            # - task: SqlAzureDacpacDeployment@1
            #   inputs:
            #     azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
            #     AuthenticationType: 'connectionString'
            #     ConnectionString: '$(ConnectionStrings)'
            #     deployType: 'SqlTask'
            #     SqlFile: '$(Pipeline.Workspace)/capstone.web.db/capstone.web.db.sql'
            #   displayName: '3.1.5. Deploy: Update Database'

    - deployment: deploy_capstone_prod_frontend
      displayName: '3.2. Deploy FrontEnd to Prod'
      dependsOn: deploy_capstone_prod_backend
      environment: prod
      strategy:
        runOnce:
          deploy:
            steps:
              - download: none

              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'current'
                  artifactName: 'capstone.web'
                  targetPath: '$(Pipeline.Workspace)/capstone.web'
                displayName: '3.2.1. Retrieve: Download Pipeline Artifacts'

              - task: ExtractFiles@1
                inputs:
                  archiveFilePatterns: '$(Pipeline.Workspace)/capstone.web/*.zip'
                  destinationFolder: '$(Pipeline.Workspace)/capstone.web/dist'
                displayName: '3.2.2. Retrieve: Extract Artifacts'

              - task: replacetokens@3
                inputs:
                  targetFiles: '$(Pipeline.Workspace)/capstone.web/dist/**/main*.js'
                  encoding: 'auto'
                  writeBOM: true
                  verbosity: 'detailed'
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
                  useLegacyPattern: false
                  enableTelemetry: true
                displayName: '3.2.3. Replace: Replace BackEnd URL'

              - task: ArchiveFiles@2
                inputs:
                  rootFolderOrFile: '$(Pipeline.Workspace)/capstone.web/dist'
                  includeRootFolder: false
                  archiveType: 'zip'
                  archiveFile: '$(Pipeline.Workspace)/capstone.web/FrontEnd-Updated.zip'
                  verbose: true
                displayName: '3.2.4. Replace: Create Archive Package in Pipeline Directory'

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'Capstone-2024-SS-2' # Has to be a literal https://github.com/microsoft/azure-pipelines-tasks/issues/14365
                  appType: 'webAppLinux'
                  appName: '$(deployFrontEnd)'
                  package: '$(Pipeline.Workspace)/FrontEnd/FrontEnd-Updated.zip' 
                  deploymentMethod: 'auto'
                displayName: '3.2.5. Deploy: Deploy Azure Web App for Linux'
